### ISSUE TITLE
来拿生物演示实验荣誉证书

### ISSUE THREAD

**Issue by SuperKenVery** [MichaelMengy/AutoPowerOff-For-classroom-computer#1]
![CE2CA78C-84CF-40BB-B2C2-6FFFA1DB7434](https://user-images.githubusercontent.com/39673849/123496808-81ec1480-d65c-11eb-8fb2-e2f5521a9ca7.jpeg)

只有你微信没有你邮箱……

**Comment by MichaelMengy** [comment]
艹 XD
